baseURL = "https://obrazslov.ru/"
languageCode = "ru-ru"
title = "Образ слов"

[params]
  description = "Мультипортал объединяет несколько сайтов и сообществ, расположенных на этом домене"
  author = "НП «Общественное благополучие Воронежа»"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
